server:
  port: 8089

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user
    username: postgres
    password: kishor@2233#
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: "*"